scalar Decimal
scalar ID

schema {
  query: Input
}

type Input {
  cart: Cart!
  discount: Discount!
}

type Cart {
  lines: [CartLine!]!
  cost: CartCost!
  attributes: [CartAttribute!]!
  buyerIdentity: CartBuyerIdentity!
}

type CartLine {
  id: ID!
  quantity: Int!
  merchandise: Merchandise!
  cost: CartLineCost!
  sellingPlanAllocation: SellingPlanAllocation
}

union Merchandise = ProductVariant

type ProductVariant {
  id: ID!
  product: Product!
}

type Product {
  id: ID!
  tags: [String!]!
}

type CartCost {
  subtotalAmount: MoneyV2!
}

type CartLineCost {
  totalAmount: MoneyV2!
}

type MoneyV2 {
  amount: Decimal!
  currencyCode: String!
}

type CartAttribute {
  key: String!
  value: String
}

type CartBuyerIdentity {
  customer: Customer
  email: String
  countryCode: String
}

type Customer {
  numberOfOrders: Int!
  amountSpent: MoneyV2!
}

type SellingPlanAllocation {
  sellingPlan: SellingPlan!
}

type SellingPlan {
  id: ID!
}

type Discount {
  discountClasses: [DiscountClass!]!
  metafield(namespace: String!, key: String!): Metafield
}

enum DiscountClass {
  PRODUCT
  ORDER
  SHIPPING
}

type Metafield {
  value: String!
}

type CartLinesDiscountsGenerateRunResult {
  operations: [CartOperation!]!
}

union CartOperation = ProductDiscountsAddOperation

type ProductDiscountsAddOperation {
  productDiscountsAdd: ProductDiscountsAdd!
}

type ProductDiscountsAdd {
  candidates: [ProductDiscountCandidate!]!
  selectionStrategy: ProductDiscountSelectionStrategy!
}

enum ProductDiscountSelectionStrategy {
  ALL
  FIRST
  MAXIMUM
}

type ProductDiscountCandidate {
  targets: [ProductDiscountCandidateTarget!]!
  value: ProductDiscountCandidateValue!
  message: String
}

union ProductDiscountCandidateTarget = ProductDiscountCandidateCartLineTarget

type ProductDiscountCandidateCartLineTarget {
  cartLine: ProductDiscountCandidateCartLine!
}

type ProductDiscountCandidateCartLine {
  id: ID!
  quantity: Int
}

union ProductDiscountCandidateValue = ProductDiscountCandidatePercentage

type ProductDiscountCandidatePercentage {
  percentage: ProductDiscountCandidatePercentageValue!
}

type ProductDiscountCandidatePercentageValue {
  value: Decimal!
}
