api_version = "2025-07"

[[extensions]]
type = "function"
name = "HPN Discount Function"
handle = "hpn-discount-function"
uid = "de6cdaf3-253c-88a0-f7b3-33911939c29ca783c038"

[[extensions.targeting]]
module = "./src/index.js"
target = "purchase.product-discount.run"
input_query = "./src/run.graphql"
export = "run"
