api_version = "2026-04"

[[extensions]]
type = "function"
name = "HPN Discount Function"
handle = "hpn-discount-function"
uid = "de6cdaf3-253c-88a0-f7b3-33911939c29ca783c038"

[[extensions.targeting]]
module = "./src/index.js"
target = "cart.lines.discounts.generate.run"
input_query = "./src/run.graphql"
export = "cart-lines-discounts-generate-run"

[[extensions.targeting]]
module = "./src/index.js"
target = "cart.delivery-options.discounts.generate.run"
input_query = "./src/deliveryRun.graphql"
export = "cart-delivery-options-discounts-generate-run"
