query DeliveryRunInput {
  cart {
    lines {
      quantity
      landingSourceAttribute: attribute(key: "__landing_source") {
        value
      }
      quizBundleIdAttribute: attribute(key: "_quiz_bundle_id") {
        value
      }
      quizFreeGiftAttribute: attribute(key: "_quiz_free_gift") {
        value
      }
      quizExpectedPaidCountAttribute: attribute(key: "_quiz_expected_paid_count") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
        }
      }
    }
    deliveryGroups {
      id
    }
  }
  discount {
    discountClasses
    metafield(namespace: "hpn_scripts", key: "function_configuration") {
      value
    }
  }
}
