query RunInput {
  cart {
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
    }
    buyerIdentity {
      customer {
        numberOfOrders
        amountSpent {
          amount
          currencyCode
        }
      }
      email
    }
    lines {
      id
      quantity
      cost {
        totalAmount {
          amount
          currencyCode
        }
      }
      sellingPlanAllocation {
        sellingPlan {
          id
        }
      }
      attribute(key: "__bundle_type") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(namespace: "hpn_scripts", key: "function_configuration") {
      value
    }
  }
}
